crud_project/urls.py
from django.contrib import admin
from django.urls import path
from record_manager import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('add_student/', views.add_student),
    path('records/', views.records),
    path('edit_record/<int:id>', views.edit_record),
    path('update_record/<int:id>', views.update_record),
    path('del_record/<int:id>', views.del_record)
    
]

record_manager/models.py
from django.db import models
from django.core.exceptions import ValidationError
import re

def validate_phone_number(value):
    if not re.match(r'^\+\d{1,15}$', value):
        raise ValidationError('Phone number must start with "+" and followed by the country code and digits.')

class Student(models.Model):
    id = models.IntegerField(primary_key=True)
    First_name = models.CharField(max_length=50)
    Last_name = models.CharField(max_length=50)
    Age = models.IntegerField()
    Email = models.EmailField()
    Phone = models.CharField(max_length=16, validators=[validate_phone_number])
    Location = models.CharField(max_length=255)
    Hobby = models.CharField(max_length=255)


    def __str__(self) -> str:
        return "{} {}".format(self.First_name, self.Last_name)

record_manager/forms.py
from django import forms
from .models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = "__all__"
        widgets = {
            'Phone': forms.TextInput(attrs={
                'pattern': r'^\+\d{1,15}$', 
                'title': 'Phone number must start with "+" and followed by the country code and digits.'
                }
            ),

        }

    
       

record_manager/views.py
from django.shortcuts import render, redirect
from .forms import StudentForm
from .models import Student


def index(request):
    return render(request, 'index.html')

def add_student(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/records')
            except Exception:
                pass
    else:
        form = StudentForm()
    return render(request, 'add_student.html', {'form':form})

def records(request):
    students = Student.objects.all()
    no_record = not students.exists()
    return render(request, 'records.html', {'students':students, 'no_record': no_record})

def edit_record(request, id):
    student = Student.objects.get(id=id)
    return render(request, 'edit_record.html', {'student':student})

def update_record(request, id):
    student = Student.objects.get(id=id)
    form = StudentForm(request.POST, instance=student)
    if form.is_valid():
        form.save()
        return redirect('/records')
    return render(request, 'edit_record.html', {'student':student})

def del_record(request, id):
    student = Student.objects.get(id=id)
    student.delete()
    return redirect('/records')

record_manager/templates/add_student.html
<!DOCTYPE html>
<html lang="en">  
    <head>  
        <meta charset="UTF-8">
        <title>Index</title>
    </head>  
    <body>  
        <form method="POST" class="post-form" action="/add_student/">  
                {% csrf_token %}  
            <div class="container"> 
                <center><table border="1px"> 
                    <thead>
                        <h3>Enter Student Details</h3>
                    </thead>

                    <tbody>
                        <tr>
                            <td>
                                ID: {{ form.id }}
                                First_name: {{form.First_name }}
                                Last_name: {{form.Last_name }}
                            </td>
                        </tr>   
                        <tr>
                            <td>
                                Age: {{ form.Age }}
                                Email: {{ form.Email }}
                                Phone: {{ form.Phone }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Location: {{ form.Location }}
                                Hobby: {{ form.Hobby }}
                            </td>
                        </tr>
                    </tbody>
                </table> 
                <br>
                <button type="submit" class="btn btn-success">Submit</button>  
                </center>  
            </div>  
        </form>  
    </body>  
</html>  

record_manager/templates/edit_record.html
<!DOCTYPE html>  
<html lang="en">  
  <head>  
      <meta charset="UTF-8">  
      <title>Index</title> 
  </head>  
  <body>
    <form method="POST" class="post-form" action="/update_record/{{student.id}}">
      {% csrf_token %}    
      <div class="container">  
        <center>
          <h3>Update Student Details</h3>
            <label>ID:</label>
              <input type="text" name="id" id="id_id" required maxlength="20" value="{{ student.id }}"/>  
            <label>First_name:</label>  
              <input type="text" name="First_name" id="id_First_name" required maxlength="100" value="{{ Student.First_name }}" placeholder="first_name" />  
            <br>
            <br>
            <label>Last_name:</label>  
              <input type="text" name="Last_name" id="id_Last_name" required maxlength="100" value="{{ Student.Last_name }}"  placeholder="last_name"/> 
            <label>Age:</label>  
              <input type="age" name="Age" id="id_Age" required maxlength="15" value="{{ Student.Age }}" placeholder="Your age"/>
            <br>
            <br>
            <label>Email:</label>  
              <input type="email" name="Email" id="id_Email" required maxlength="100" value="{{ Student.Email }}" placeholder=" email" /> 
            <label>Phone:</label>  
              <input type="tel" name="Phone" id="id_Phone" value="{{ Student.Phone }}" placeholder="e.g +666666" pattern="^\+234\d{10,15}" required /> 
            <br>
            <br>
            <label>Location:</label>  
              <input type="text" name="Location" id="id_Location" required maxlength="15" value="{{ Student.Location }}" placeholder="location" /> 
            <label>Hobby:</label>  
              <input type="text" name="Hobby" id="id_Hobby" required maxlength="15" value="{{ Stuent.Hobby }}" placeholder="hobby"/> 
            
              <br>
              <br> 
          <button type="submit" class="btn btn-success">Update</button>
      </center> 
      </div> 
    </form>  
  </body>  
</html>  

record_manager/templates/index.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <title>CRUD PROJECT</title>
    </head>
    <body style="background-color: bisque;">
        <div style="background-color: black; text-align: center; margin: 250px; padding: 10px; border-radius: 10px;"
        title="click on CRUD PROJECT">
            <p style="color: aliceblue;">To start project - Kindly click on CRUD PROJECT </p>
            <a href="records/" style=" font-size: 40px; text-decoration: none;" >CRUD PROJECT</a>
            <p style="color: aliceblue;">OLAYIWOLA SULAIMON - CDTC0348</p>
        </div>
        <div>
            
        </div>
    </body>
</html>

record_manager/templates/records.html
<!DOCTYPE html>  
<html lang="en">  
    <head>  
        <meta charset="UTF-8">  
        <title>Student Records</title> 
    </head>  
    <body> 
        <h2><center>Students Management Record</center></h2> 
        <center>
            <table border="1px">  
                <thead style="background-color: whitesmoke;">  
                    <tr>  
                        <th>ID</th>  
                        <th>First_name</th>  
                        <th>Last_name</th>  
                        <th>Age</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Location</th>
                        <th>Hobby</th>
                        <th>Actions</th>  
                    </tr>  
                </thead> 

                <tbody>
                    {% if no_record %}
                    <p><b>No records found</b></p>
                    {% else %}
                    {% for student in students %}  
                    <tr>  
                        <td><center>{{ student.id }}</center></td>  
                        <td><center>{{ student.First_name }}</center></td>  
                        <td><center>{{ student.Last_name }}</center></td>  
                        <td><center>{{ student.Age }}</center></td>
                        <td><center>{{ student.Email }}</center></td>
                        <td><center>{{ student.Phone }}</center></td>
                        <td><center>{{ student.Location }}</center></td>
                        <td><center>{{ student.Hobby }}</center></td>

                        <td>  
                            <a href="/edit_record/{{ student.id }}" style="text-decoration: none;">Edit</a>  
                            <a href="/del_record/{{ student.id }}" style="text-decoration: none;">Delete</a>  
                        </td>  
                    </tr>  
                    {% endfor %}
                    {% endif %}  
                </tbody>  
            </table>
        </center>

        <br>  
        <br>
        
        <center>
            <table style="background-color: black; border-radius: 10px; padding: 5px;">
            <td>
                <a href="/add_student/" class="btn btn-success" style="color: blanchedalmond;
                text-decoration: none; font-size: 20px;" >Add New Record</a>  
            </td>
            </table>
        </center>

    </body>  
</html>  